import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { ThemeProvider } from '@/features'
import {
  Header,
  SearchBar,
  CategoriesBar,
  MobileBottomNav,
  BottomSheet,
} from '@/widgets'
import { Inter, Bungee } from 'next/font/google'
import "./globals.css"

// Инициализируем шрифт.
// subsets: ['latin'] — обязательный параметр для оптимизации загрузки.
// display: 'swap' добавляется автоматически.
const inter = Inter({
  variable: "--font-inter-sans",
  subsets: ['latin']
})

const bungee = Bungee({
  variable: "--font-bungee-sans",
  subsets: ['latin'],
  weight: ["400"]
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Womem",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <html
        lang="en"
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${bungee.variable}
          ${inter.variable}
          h-full
          antialiased
        `}
      >
        <body
          className={`
            min-h-full
            flex
            flex-col
            bg-[var(--color-bg)]
            text-[var(--color-text)]
          `}
        >

          {children}
          {modal}

          <BottomSheet />
        </body>
      </html>
    </ThemeProvider>
  );
}
